from models.model import Model
from tensorflow.keras import Sequential, layers, models
from tensorflow.keras.layers.experimental.preprocessing import Rescaling
from tensorflow.keras.optimizers import RMSprop, Adam

class TransferedModel(Model):
    def _define_model(self, input_shape, categories_count):
        # Your code goes here
        # you have to initialize self.model to a keras model
        # load your basic model with keras's load_model function
        # freeze the weights of the loaded model to make sure the training doesn't affect them
        # (check the number of total params, trainable params and non-trainable params in your summary generated by train_transfer.py)
        # use this model by removing the last layer, adding dense layers and an output layer

        self.model = models.load_model("./submissions/Step6/basic_model_100_epochs_timestamp_1771325387.keras",compile=False)
        for layer in self.model.layers:
            layer.trainable = False
        self.model.pop()     
        self.model.add(layers.Dense(16,activation='relu', name='dense2'))
        self.model.add(layers.Dense(32,activation='relu'))
        self.model.add(layers.Dense(categories_count,activation='softmax'))



    
    def _compile_model(self):
        # Your code goes here
        # you have to compile the keras model, similar to the example in the writeup
       self.model.compile(
           optimizer=Adam(learning_rate=0.001),
           loss='categorical_crossentropy',
           metrics=['accuracy'],
       )

